In [1]:
import pandas as pd

In [12]:
#Pandas series => one row dataframe is a series 
a= [1,2,3]
myvar = pd.Series(a)
type(myvar)
print(myvar)

0    1
1    2
2    3
dtype: int64

In [13]:
my_var = pd.Series(a, index=["x", "y", "z"]) # Custom index 
my_var

x    1
y    2
z    3
dtype: int64

### DataFrame

In [15]:
#baisc Dataframe 
data ={
    "calories" : [420,300,524],
    "duration":[45,26,23]
}
df_run = pd.DataFrame(data)
df_run

   calories  duration
0       420        45
1       300        26
2       524        23

In [5]:
#import dataset from folders or directory
df = pd.read_csv("Dataset/1_Sales.csv") # Importing CSV dataset

In [6]:
df

   SalesRep Region Month    Sales  Units Sold
0       Amy  North   Jan  23040.0       239.0
1       Amy  North   Feb  24131.0        79.0
2       Amy  North   Mar  24646.0        71.0
3       Amy  North   Apr  22047.0        71.0
4       Amy  North   May  24971.0         NaN
5       Amy  North   Jun  24218.0        92.0
6       Amy  North   Jul  25735.0       175.0
7       Amy  North   Aug      NaN        87.0
8       Amy  North   Sep  25749.0       557.0
9       Amy  North   Oct  24437.0        95.0
10      Amy  North   Nov  25355.0       706.0
11      Amy  North   Dec  25899.0       180.0
12      Bob  North   Jan  20024.0       103.0
13      Bob  North   Feb  23822.0       267.0
14      Bob  North   Mar  24854.0        96.0
15      Bob  North   Apr  22838.0        74.0
16      Bob  North   May  25320.0       231.0
17      Bob  North   Jun  24733.0       164.0
18      Bob  North   Jul  21184.0        68.0
19      Bob  North   Aug  23174.0       114.0
20      Bob  North   Sep  25999.0        84.0
21      Bob  North   Oct  22639.0       260.0
22      Bob  North   Nov  23949.0       109.0
23      Bob  North   Dec  23179.0       465.0
24    Chuck  South   Jan  19886.0        95.0
25    Chuck  South   Feb  23494.0       148.0
26    Chuck  South   Mar  21824.0        83.0
27    Chuck  South   Apr  22058.0        96.0
28    Chuck  South   May  20280.0       453.0
29    Chuck  South   Jun  23965.0       760.0
30    Chuck  South   Jul  23032.0       155.0
31    Chuck  South   Aug  21273.0       769.0
32    Chuck  South   Sep  21584.0       114.0
33    Chuck  South   Oct  19625.0        83.0
34    Chuck  South   Nov  19832.0        70.0
35    Chuck  South   Dec  20583.0       178.0
36     Doug  South   Jan  26264.0        92.0
37     Doug  South   Feb  29953.0       852.0
38     Doug  South   Mar  25041.0        86.0
39     Doug  South   Apr  29338.0       223.0
40     Doug  South   May  25150.0       242.0
41     Doug  South   Jun  27371.0        95.0
42     Doug  South   Jul  25044.0        82.0
43     Doug  South   Aug  29506.0       103.0
44     Doug  South   Sep  29061.0       146.0
45     Doug  South   Oct  27113.0       120.0
46     Doug  South   Nov  25953.0        81.0
47     Doug  South   Dec  28670.0       198.0

In [17]:
pd.options.display.max_rows = 9999

In [22]:
df.head()

  SalesRep Region Month    Sales  Units Sold
0      Amy  North   Jan  23040.0       239.0
1      Amy  North   Feb  24131.0        79.0
2      Amy  North   Mar  24646.0        71.0
3      Amy  North   Apr  22047.0        71.0
4      Amy  North   May  24971.0         NaN

In [24]:
df.tail()

   SalesRep Region Month    Sales  Units Sold
43     Doug  South   Aug  29506.0       103.0
44     Doug  South   Sep  29061.0       146.0
45     Doug  South   Oct  27113.0       120.0
46     Doug  South   Nov  25953.0        81.0
47     Doug  South   Dec  28670.0       198.0

In [29]:
df_json= pd.read_json("Dataset/iris.json")
df_json

     sepalLength  sepalWidth  petalLength  petalWidth     species
0            5.1         3.5          1.4         0.2      setosa
1            4.9         3.0          1.4         0.2      setosa
2            4.7         3.2          1.3         0.2      setosa
3            4.6         3.1          1.5         0.2      setosa
4            5.0         3.6          1.4         0.2      setosa
5            5.4         3.9          1.7         0.4      setosa
6            4.6         3.4          1.4         0.3      setosa
7            5.0         3.4          1.5         0.2      setosa
8            4.4         2.9          1.4         0.2      setosa
9            4.9         3.1          1.5         0.1      setosa
10           5.4         3.7          1.5         0.2      setosa
11           4.8         3.4          1.6         0.2      setosa
12           4.8         3.0          1.4         0.1      setosa
13           4.3         3.0          1.1         0.1      setosa
14           5.8         4.0          1.2         0.2      setosa
15           5.7         4.4          1.5         0.4      setosa
16           5.4         3.9          1.3         0.4      setosa
17           5.1         3.5          1.4         0.3      setosa
18           5.7         3.8          1.7         0.3      setosa
19           5.1         3.8          1.5         0.3      setosa
20           5.4         3.4          1.7         0.2      setosa
21           5.1         3.7          1.5         0.4      setosa
22           4.6         3.6          1.0         0.2      setosa
23           5.1         3.3          1.7         0.5      setosa
24           4.8         3.4          1.9         0.2      setosa
25           5.0         3.0          1.6         0.2      setosa
26           5.0         3.4          1.6         0.4      setosa
27           5.2         3.5          1.5         0.2      setosa
28           5.2         3.4          1.4         0.2      setosa
29           4.7         3.2          1.6         0.2      setosa
30           4.8         3.1          1.6         0.2      setosa
31           5.4         3.4          1.5         0.4      setosa
32           5.2         4.1          1.5         0.1      setosa
33           5.5         4.2          1.4         0.2      setosa
34           4.9         3.1          1.5         0.2      setosa
35           5.0         3.2          1.2         0.2      setosa
36           5.5         3.5          1.3         0.2      setosa
37           4.9         3.6          1.4         0.1      setosa
38           4.4         3.0          1.3         0.2      setosa
39           5.1         3.4          1.5         0.2      setosa
40           5.0         3.5          1.3         0.3      setosa
41           4.5         2.3          1.3         0.3      setosa
42           4.4         3.2          1.3         0.2      setosa
43           5.0         3.5          1.6         0.6      setosa
44           5.1         3.8          1.9         0.4      setosa
45           4.8         3.0          1.4         0.3      setosa
46           5.1         3.8          1.6         0.2      setosa
47           4.6         3.2          1.4         0.2      setosa
48           5.3         3.7          1.5         0.2      setosa
49           5.0         3.3          1.4         0.2      setosa
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
55           5.7         2.8          4.5         1.3  versicolor
56           6.3         3.3          4.7         1.6  versicolor
57           4.9         2.4          3.3         1.0  versicolor
58           6.6         2.9          4.6         1.3  versicolor
59           5.2         2.7          3.9         1.4  versicolor
60           5.0         2.0          3.5         1.0  versicolor
61           5.9         3.0          4.2         1.5  versicolor
62           6.0         2.2          4.0         1.0  versicolor
63           6.1         2.9          4.7         1.4  versicolor
64           5.6         2.9          3.6         1.3  versicolor
65           6.7         3.1          4.4         1.4  versicolor
66           5.6         3.0          4.5         1.5  versicolor
67           5.8         2.7          4.1         1.0  versicolor
68           6.2         2.2          4.5         1.5  versicolor
69           5.6         2.5          3.9         1.1  versicolor
70           5.9         3.2          4.8         1.8  versicolor
71           6.1         2.8          4.0         1.3  versicolor
72           6.3         2.5          4.9         1.5  versicolor
73           6.1         2.8          4.7         1.2  versicolor
74           6.4         2.9          4.3         1.3  versicolor
75           6.6         3.0          4.4         1.4  versicolor
76           6.8         2.8          4.8         1.4  versicolor
77           6.7         3.0          5.0         1.7  versicolor
78           6.0         2.9          4.5         1.5  versicolor
79           5.7         2.6          3.5         1.0  versicolor
80           5.5         2.4          3.8         1.1  versicolor
81           5.5         2.4          3.7         1.0  versicolor
82           5.8         2.7          3.9         1.2  versicolor
83           6.0         2.7          5.1         1.6  versicolor
84           5.4         3.0          4.5         1.5  versicolor
85           6.0         3.4          4.5         1.6  versicolor
86           6.7         3.1          4.7         1.5  versicolor
87           6.3         2.3          4.4         1.3  versicolor
88           5.6         3.0          4.1         1.3  versicolor
89           5.5         2.5          4.0         1.3  versicolor
90           5.5         2.6          4.4         1.2  versicolor
91           6.1         3.0          4.6         1.4  versicolor
92           5.8         2.6          4.0         1.2  versicolor
93           5.0         2.3          3.3         1.0  versicolor
94           5.6         2.7          4.2         1.3  versicolor
95           5.7         3.0          4.2         1.2  versicolor
96           5.7         2.9          4.2         1.3  versicolor
97           6.2         2.9          4.3         1.3  versicolor
98           5.1         2.5          3.0         1.1  versicolor
99           5.7         2.8          4.1         1.3  versicolor
100          6.3         3.3          6.0         2.5   virginica
101          5.8         2.7          5.1         1.9   virginica
102          7.1         3.0          5.9         2.1   virginica
103          6.3         2.9          5.6         1.8   virginica
104          6.5         3.0          5.8         2.2   virginica
105          7.6         3.0          6.6         2.1   virginica
106          4.9         2.5          4.5         1.7   virginica
107          7.3         2.9          6.3         1.8   virginica
108          6.7         2.5          5.8         1.8   virginica
109          7.2         3.6          6.1         2.5   virginica
110          6.5         3.2          5.1         2.0   virginica
111          6.4         2.7          5.3         1.9   virginica
112          6.8         3.0          5.5         2.1   virginica
113          5.7         2.5          5.0         2.0   virginica
114          5.8         2.8          5.1         2.4   virginica
115          6.4         3.2          5.3         2.3   virginica
116          6.5         3.0          5.5         1.8   virginica
117          7.7         3.8          6.7         2.2   virginica
118          7.7         2.6          6.9         2.3   virginica
119          6.0         2.2          5.0         1.5   virginica
120          6.9         3.2          5.7         2.3   virginica
121          5.6         2.8          4.9         2.0   virginica
122          7.7         2.8          6.7         2.0   virginica
123          6.3         2.7          4.9         1.8   virginica
124          6.7         3.3          5.7         2.1   virginica
125          7.2         3.2          6.0         1.8   virginica
126          6.2         2.8          4.8         1.8   virginica
127          6.1         3.0          4.9         1.8   virginica
128          6.4         2.8          5.6         2.1   virginica
129          7.2         3.0          5.8         1.6   virginica
130          7.4         2.8          6.1         1.9   virginica
131          7.9         3.8          6.4         2.0   virginica
132          6.4         2.8          5.6         2.2   virginica
133          6.3         2.8          5.1         1.5   virginica
134          6.1         2.6          5.6         1.4   virginica
135          7.7         3.0          6.1         2.3   virginica
136          6.3         3.4          5.6         2.4   virginica
137          6.4         3.1          5.5         1.8   virginica
138          6.0         3.0          4.8         1.8   virginica
139          6.9         3.1          5.4         2.1   virginica
140          6.7         3.1          5.6         2.4   virginica
141          6.9         3.1          5.1         2.3   virginica
142          5.8         2.7          5.1         1.9   virginica
143          6.8         3.2          5.9         2.3   virginica
144          6.7         3.3          5.7         2.5   virginica
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

In [30]:
print(df_json.to_string())

     sepalLength  sepalWidth  petalLength  petalWidth     species
0            5.1         3.5          1.4         0.2      setosa
1            4.9         3.0          1.4         0.2      setosa
2            4.7         3.2          1.3         0.2      setosa
3            4.6         3.1          1.5         0.2      setosa
4            5.0         3.6          1.4         0.2      setosa
5            5.4         3.9          1.7         0.4      setosa
6            4.6         3.4          1.4         0.3      setosa
7            5.0         3.4          1.5         0.2      setosa
8            4.4         2.9          1.4         0.2      setosa
9            4.9         3.1          1.5         0.1      setosa
10           5.4         3.7          1.5         0.2      setosa
11           4.8         3.4          1.6         0.2      setosa
12           4.8         3.0          1.4         0.1      setosa
13           4.3         3.0          1.1         0.1      setosa
14           5.8         4.0          1.2         0.2      setosa
15           5.7         4.4          1.5         0.4      setosa
16           5.4         3.9          1.3         0.4      setosa
17           5.1         3.5          1.4         0.3      setosa
18           5.7         3.8          1.7         0.3      setosa
19           5.1         3.8          1.5         0.3      setosa
20           5.4         3.4          1.7         0.2      setosa
21           5.1         3.7          1.5         0.4      setosa
22           4.6         3.6          1.0         0.2      setosa
23           5.1         3.3          1.7         0.5      setosa
24           4.8         3.4          1.9         0.2      setosa
25           5.0         3.0          1.6         0.2      setosa
26           5.0         3.4          1.6         0.4      setosa
27           5.2         3.5          1.5         0.2      setosa
28           5.2         3.4          1.4         0.2      setosa
29           4.7         3.2          1.6         0.2      setosa
30           4.8         3.1          1.6         0.2      setosa
31           5.4         3.4          1.5         0.4      setosa
32           5.2         4.1          1.5         0.1      setosa
33           5.5         4.2          1.4         0.2      setosa
34           4.9         3.1          1.5         0.2      setosa
35           5.0         3.2          1.2         0.2      setosa
36           5.5         3.5          1.3         0.2      setosa
37           4.9         3.6          1.4         0.1      setosa
38           4.4         3.0          1.3         0.2      setosa
39           5.1         3.4          1.5         0.2      setosa
40           5.0         3.5          1.3         0.3      setosa
41           4.5         2.3          1.3         0.3      setosa
42           4.4         3.2          1.3         0.2      setosa
43           5.0         3.5          1.6         0.6      setosa
44           5.1         3.8          1.9         0.4      setosa
45           4.8         3.0          1.4         0.3      setosa
46           5.1         3.8          1.6         0.2      setosa
47           4.6         3.2          1.4         0.2      setosa
48           5.3         3.7          1.5         0.2      setosa
49           5.0         3.3          1.4         0.2      setosa
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
55           5.7         2.8          4.5         1.3  versicolor
56           6.3         3.3          4.7         1.6  versicolor
57           4.9         2.4          3.3         1.0  versicolor
58           6.6         2.9          4.6         1.3  versicolor
59           5.2         2.7          3.9         1.4  versicolor
60           5.0         2.0          3.5         1.0  versicolor
61           5.9         3.0          4.2         1.5  versicolor
62           6.0         2.2          4.0         1.0  versicolor
63           6.1         2.9          4.7         1.4  versicolor
64           5.6         2.9          3.6         1.3  versicolor
65           6.7         3.1          4.4         1.4  versicolor
66           5.6         3.0          4.5         1.5  versicolor
67           5.8         2.7          4.1         1.0  versicolor
68           6.2         2.2          4.5         1.5  versicolor
69           5.6         2.5          3.9         1.1  versicolor
70           5.9         3.2          4.8         1.8  versicolor
71           6.1         2.8          4.0         1.3  versicolor
72           6.3         2.5          4.9         1.5  versicolor
73           6.1         2.8          4.7         1.2  versicolor
74           6.4         2.9          4.3         1.3  versicolor
75           6.6         3.0          4.4         1.4  versicolor
76           6.8         2.8          4.8         1.4  versicolor
77           6.7         3.0          5.0         1.7  versicolor
78           6.0         2.9          4.5         1.5  versicolor
79           5.7         2.6          3.5         1.0  versicolor
80           5.5         2.4          3.8         1.1  versicolor
81           5.5         2.4          3.7         1.0  versicolor
82           5.8         2.7          3.9         1.2  versicolor
83           6.0         2.7          5.1         1.6  versicolor
84           5.4         3.0          4.5         1.5  versicolor
85           6.0         3.4          4.5         1.6  versicolor
86           6.7         3.1          4.7         1.5  versicolor
87           6.3         2.3          4.4         1.3  versicolor
88           5.6         3.0          4.1         1.3  versicolor
89           5.5         2.5          4.0         1.3  versicolor
90           5.5         2.6          4.4         1.2  versicolor
91           6.1         3.0          4.6         1.4  versicolor
92           5.8         2.6          4.0         1.2  versicolor
93           5.0         2.3          3.3         1.0  versicolor
94           5.6         2.7          4.2         1.3  versicolor
95           5.7         3.0          4.2         1.2  versicolor
96           5.7         2.9          4.2         1.3  versicolor
97           6.2         2.9          4.3         1.3  versicolor
98           5.1         2.5          3.0         1.1  versicolor
99           5.7         2.8          4.1         1.3  versicolor
100          6.3         3.3          6.0         2.5   virginica
101          5.8         2.7          5.1         1.9   virginica
102          7.1         3.0          5.9         2.1   virginica
103          6.3         2.9          5.6         1.8   virginica
104          6.5         3.0          5.8         2.2   virginica
105          7.6         3.0          6.6         2.1   virginica
106          4.9         2.5          4.5         1.7   virginica
107          7.3         2.9          6.3         1.8   virginica
108          6.7         2.5          5.8         1.8   virginica
109          7.2         3.6          6.1         2.5   virginica
110          6.5         3.2          5.1         2.0   virginica
111          6.4         2.7          5.3         1.9   virginica
112          6.8         3.0          5.5         2.1   virginica
113          5.7         2.5          5.0         2.0   virginica
114          5.8         2.8          5.1         2.4   virginica
115          6.4         3.2          5.3         2.3   virginica
116          6.5         3.0          5.5         1.8   virginica
117          7.7         3.8          6.7         2.2   virginica
118          7.7         2.6          6.9         2.3   virginica
119          6.0         2.2          5.0         1.5   virginica
120          6.9         3.2          5.7         2.3   virginica
121          5.6         2.8          4.9         2.0   virginica
122          7.7         2.8          6.7         2.0   virginica
123          6.3         2.7          4.9         1.8   virginica
124          6.7         3.3          5.7         2.1   virginica
125          7.2         3.2          6.0         1.8   virginica
126          6.2         2.8          4.8         1.8   virginica
127          6.1         3.0          4.9         1.8   virginica
128          6.4         2.8          5.6         2.1   virginica
129          7.2         3.0          5.8         1.6   virginica
130          7.4         2.8          6.1         1.9   virginica
131          7.9         3.8          6.4         2.0   virginica
132          6.4         2.8          5.6         2.2   virginica
133          6.3         2.8          5.1         1.5   virginica
134          6.1         2.6          5.6         1.4   virginica
135          7.7         3.0          6.1         2.3   virginica
136          6.3         3.4          5.6         2.4   virginica
137          6.4         3.1          5.5         1.8   virginica
138          6.0         3.0          4.8         1.8   virginica
139          6.9         3.1          5.4         2.1   virginica
140          6.7         3.1          5.6         2.4   virginica
141          6.9         3.1          5.1         2.3   virginica
142          5.8         2.7          5.1         1.9   virginica
143          6.8         3.2          5.9         2.3   virginica
144          6.7         3.3          5.7         2.5   virginica
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

In [31]:
print(df.to_string())

   SalesRep Region Month    Sales  Units Sold
0       Amy  North   Jan  23040.0       239.0
1       Amy  North   Feb  24131.0        79.0
2       Amy  North   Mar  24646.0        71.0
3       Amy  North   Apr  22047.0        71.0
4       Amy  North   May  24971.0         NaN
5       Amy  North   Jun  24218.0        92.0
6       Amy  North   Jul  25735.0       175.0
7       Amy  North   Aug      NaN        87.0
8       Amy  North   Sep  25749.0       557.0
9       Amy  North   Oct  24437.0        95.0
10      Amy  North   Nov  25355.0       706.0
11      Amy  North   Dec  25899.0       180.0
12      Bob  North   Jan  20024.0       103.0
13      Bob  North   Feb  23822.0       267.0
14      Bob  North   Mar  24854.0        96.0
15      Bob  North   Apr  22838.0        74.0
16      Bob  North   May  25320.0       231.0
17      Bob  North   Jun  24733.0       164.0
18      Bob  North   Jul  21184.0        68.0
19      Bob  North   Aug  23174.0       114.0
20      Bob  North   Sep  25999.0        84.0
21      Bob  North   Oct  22639.0       260.0
22      Bob  North   Nov  23949.0       109.0
23      Bob  North   Dec  23179.0       465.0
24    Chuck  South   Jan  19886.0        95.0
25    Chuck  South   Feb  23494.0       148.0
26    Chuck  South   Mar  21824.0        83.0
27    Chuck  South   Apr  22058.0        96.0
28    Chuck  South   May  20280.0       453.0
29    Chuck  South   Jun  23965.0       760.0
30    Chuck  South   Jul  23032.0       155.0
31    Chuck  South   Aug  21273.0       769.0
32    Chuck  South   Sep  21584.0       114.0
33    Chuck  South   Oct  19625.0        83.0
34    Chuck  South   Nov  19832.0        70.0
35    Chuck  South   Dec  20583.0       178.0
36     Doug  South   Jan  26264.0        92.0
37     Doug  South   Feb  29953.0       852.0
38     Doug  South   Mar  25041.0        86.0
39     Doug  South   Apr  29338.0       223.0
40     Doug  South   May  25150.0       242.0
41     Doug  South   Jun  27371.0        95.0
42     Doug  South   Jul  25044.0        82.0
43     Doug  South   Aug  29506.0       103.0
44     Doug  South   Sep  29061.0       146.0
45     Doug  South   Oct  27113.0       120.0
46     Doug  South   Nov  25953.0        81.0
47     Doug  South   Dec  28670.0       198.0

### Cleaning Data
#### Data cleaning means fixing bad data from datasets like empty cells, data with wrong format, wrong data, duplicates

In [32]:
df

   SalesRep Region Month    Sales  Units Sold
0       Amy  North   Jan  23040.0       239.0
1       Amy  North   Feb  24131.0        79.0
2       Amy  North   Mar  24646.0        71.0
3       Amy  North   Apr  22047.0        71.0
4       Amy  North   May  24971.0         NaN
5       Amy  North   Jun  24218.0        92.0
6       Amy  North   Jul  25735.0       175.0
7       Amy  North   Aug      NaN        87.0
8       Amy  North   Sep  25749.0       557.0
9       Amy  North   Oct  24437.0        95.0
10      Amy  North   Nov  25355.0       706.0
11      Amy  North   Dec  25899.0       180.0
12      Bob  North   Jan  20024.0       103.0
13      Bob  North   Feb  23822.0       267.0
14      Bob  North   Mar  24854.0        96.0
15      Bob  North   Apr  22838.0        74.0
16      Bob  North   May  25320.0       231.0
17      Bob  North   Jun  24733.0       164.0
18      Bob  North   Jul  21184.0        68.0
19      Bob  North   Aug  23174.0       114.0
20      Bob  North   Sep  25999.0        84.0
21      Bob  North   Oct  22639.0       260.0
22      Bob  North   Nov  23949.0       109.0
23      Bob  North   Dec  23179.0       465.0
24    Chuck  South   Jan  19886.0        95.0
25    Chuck  South   Feb  23494.0       148.0
26    Chuck  South   Mar  21824.0        83.0
27    Chuck  South   Apr  22058.0        96.0
28    Chuck  South   May  20280.0       453.0
29    Chuck  South   Jun  23965.0       760.0
30    Chuck  South   Jul  23032.0       155.0
31    Chuck  South   Aug  21273.0       769.0
32    Chuck  South   Sep  21584.0       114.0
33    Chuck  South   Oct  19625.0        83.0
34    Chuck  South   Nov  19832.0        70.0
35    Chuck  South   Dec  20583.0       178.0
36     Doug  South   Jan  26264.0        92.0
37     Doug  South   Feb  29953.0       852.0
38     Doug  South   Mar  25041.0        86.0
39     Doug  South   Apr  29338.0       223.0
40     Doug  South   May  25150.0       242.0
41     Doug  South   Jun  27371.0        95.0
42     Doug  South   Jul  25044.0        82.0
43     Doug  South   Aug  29506.0       103.0
44     Doug  South   Sep  29061.0       146.0
45     Doug  South   Oct  27113.0       120.0
46     Doug  South   Nov  25953.0        81.0
47     Doug  South   Dec  28670.0       198.0

In [34]:
new_df = df.dropna()
new_df

   SalesRep Region Month    Sales  Units Sold
0       Amy  North   Jan  23040.0       239.0
1       Amy  North   Feb  24131.0        79.0
2       Amy  North   Mar  24646.0        71.0
3       Amy  North   Apr  22047.0        71.0
5       Amy  North   Jun  24218.0        92.0
6       Amy  North   Jul  25735.0       175.0
8       Amy  North   Sep  25749.0       557.0
9       Amy  North   Oct  24437.0        95.0
10      Amy  North   Nov  25355.0       706.0
11      Amy  North   Dec  25899.0       180.0
12      Bob  North   Jan  20024.0       103.0
13      Bob  North   Feb  23822.0       267.0
14      Bob  North   Mar  24854.0        96.0
15      Bob  North   Apr  22838.0        74.0
16      Bob  North   May  25320.0       231.0
17      Bob  North   Jun  24733.0       164.0
18      Bob  North   Jul  21184.0        68.0
19      Bob  North   Aug  23174.0       114.0
20      Bob  North   Sep  25999.0        84.0
21      Bob  North   Oct  22639.0       260.0
22      Bob  North   Nov  23949.0       109.0
23      Bob  North   Dec  23179.0       465.0
24    Chuck  South   Jan  19886.0        95.0
25    Chuck  South   Feb  23494.0       148.0
26    Chuck  South   Mar  21824.0        83.0
27    Chuck  South   Apr  22058.0        96.0
28    Chuck  South   May  20280.0       453.0
29    Chuck  South   Jun  23965.0       760.0
30    Chuck  South   Jul  23032.0       155.0
31    Chuck  South   Aug  21273.0       769.0
32    Chuck  South   Sep  21584.0       114.0
33    Chuck  South   Oct  19625.0        83.0
34    Chuck  South   Nov  19832.0        70.0
35    Chuck  South   Dec  20583.0       178.0
36     Doug  South   Jan  26264.0        92.0
37     Doug  South   Feb  29953.0       852.0
38     Doug  South   Mar  25041.0        86.0
39     Doug  South   Apr  29338.0       223.0
40     Doug  South   May  25150.0       242.0
41     Doug  South   Jun  27371.0        95.0
42     Doug  South   Jul  25044.0        82.0
43     Doug  South   Aug  29506.0       103.0
44     Doug  South   Sep  29061.0       146.0
45     Doug  South   Oct  27113.0       120.0
46     Doug  South   Nov  25953.0        81.0
47     Doug  South   Dec  28670.0       198.0